# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'gui.ui'
##
## Created by: Qt User Interface Compiler version 6.10.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QHeaderView, QLabel,
    QLineEdit, QListView, QListWidget, QListWidgetItem,
    QMainWindow, QPushButton, QScrollArea, QScrollBar,
    QSizePolicy, QStackedWidget, QStatusBar, QTableView,
    QVBoxLayout, QWidget)
import resources_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1440, 872)
        font = QFont()
        font.setPointSize(20)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet(u"background-color: rgb(237, 241, 255);")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setAutoFillBackground(False)
        self.main_menu = QWidget(self.centralwidget)
        self.main_menu.setObjectName(u"main_menu")
        self.main_menu.setGeometry(QRect(290, -90, 1121, 221))
        self.verticalLayout_3 = QVBoxLayout(self.main_menu)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.label_4 = QLabel(self.main_menu)
        self.label_4.setObjectName(u"label_4")

        self.verticalLayout_3.addWidget(self.label_4)

        self.name_widget = QWidget(self.centralwidget)
        self.name_widget.setObjectName(u"name_widget")
        self.name_widget.setGeometry(QRect(80, 0, 241, 881))
        self.name_widget.setStyleSheet(u"QWidget{\n"
"background-color: rgb(173, 207, 239);\n"
"}\n"
"\n"
"QPushButton {\n"
"	color:white;\n"
"	text-align: left;\n"
"	height: 30px;\n"
"	border:none;\n"
"	padding-left:10px;\n"
"	border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"	background-color:white;\n"
"	color: rgb(173, 207, 239);\n"
"	font-weight:bold;\n"
"}\n"
"\n"
"")
        self.layoutWidget = QWidget(self.name_widget)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(0, 20, 246, 261))
        self.Sidebar2 = QVBoxLayout(self.layoutWidget)
        self.Sidebar2.setSpacing(8)
        self.Sidebar2.setObjectName(u"Sidebar2")
        self.Sidebar2.setContentsMargins(0, 0, 0, 0)
        self.dashboard_2 = QPushButton(self.layoutWidget)
        self.dashboard_2.setObjectName(u"dashboard_2")
        self.dashboard_2.setEnabled(True)
        icon = QIcon()
        icon.addFile(u":/sidebar_images/dashboard_icon_white-removebg-preview.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon.addFile(u":/sidebar_images/dsahboard_icon_blue-removebg-preview.png", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        self.dashboard_2.setIcon(icon)
        self.dashboard_2.setIconSize(QSize(100, 100))
        self.dashboard_2.setCheckable(True)
        self.dashboard_2.setChecked(False)
        self.dashboard_2.setAutoExclusive(True)

        self.Sidebar2.addWidget(self.dashboard_2)

        self.license_2 = QPushButton(self.layoutWidget)
        self.license_2.setObjectName(u"license_2")
        icon1 = QIcon()
        icon1.addFile(u":/sidebar_images/license_management_icon_black-removebg-preview.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon1.addFile(u":/sidebar_images/license_management_icon_blue-removebg-preview.png", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        self.license_2.setIcon(icon1)
        self.license_2.setIconSize(QSize(100, 100))
        self.license_2.setCheckable(True)
        self.license_2.setAutoExclusive(True)

        self.Sidebar2.addWidget(self.license_2)

        self.RHU_2 = QPushButton(self.layoutWidget)
        self.RHU_2.setObjectName(u"RHU_2")
        icon2 = QIcon()
        icon2.addFile(u":/newPrefix/RHU_management_icon_white-removebg-preview-removebg-preview.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon2.addFile(u":/sidebar_images/RHU_management_icon_blue-removebg-preview.png", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        self.RHU_2.setIcon(icon2)
        self.RHU_2.setIconSize(QSize(100, 100))
        self.RHU_2.setCheckable(True)
        self.RHU_2.setAutoExclusive(True)

        self.Sidebar2.addWidget(self.RHU_2)

        self.allocation_2 = QPushButton(self.layoutWidget)
        self.allocation_2.setObjectName(u"allocation_2")
        icon3 = QIcon()
        icon3.addFile(u":/sidebar_images/Allocation_matching_icon_white-removebg-preview.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon3.addFile(u":/sidebar_images/Allocation_matching_icon_blue-removebg-preview.png", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        self.allocation_2.setIcon(icon3)
        self.allocation_2.setIconSize(QSize(100, 100))
        self.allocation_2.setCheckable(True)
        self.allocation_2.setAutoExclusive(True)

        self.Sidebar2.addWidget(self.allocation_2)

        self.release_2 = QPushButton(self.layoutWidget)
        self.release_2.setObjectName(u"release_2")
        icon4 = QIcon()
        icon4.addFile(u":/sidebar_images/Release_management_icon_white-removebg-preview.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon4.addFile(u":/sidebar_images/Release_management_icon_blue-removebg-preview.png", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        self.release_2.setIcon(icon4)
        self.release_2.setIconSize(QSize(100, 100))
        self.release_2.setCheckable(True)
        self.release_2.setAutoExclusive(True)

        self.Sidebar2.addWidget(self.release_2)

        self.cost_2 = QPushButton(self.layoutWidget)
        self.cost_2.setObjectName(u"cost_2")
        icon5 = QIcon()
        icon5.addFile(u":/sidebar_images/cost_tracking_icon_white__1_-removebg-preview.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon5.addFile(u":/sidebar_images/cost tracking icon blue.png", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        self.cost_2.setIcon(icon5)
        self.cost_2.setIconSize(QSize(100, 100))
        self.cost_2.setCheckable(True)
        self.cost_2.setAutoExclusive(True)

        self.Sidebar2.addWidget(self.cost_2)

        self.pushButton_14 = QPushButton(self.name_widget)
        self.pushButton_14.setObjectName(u"pushButton_14")
        self.pushButton_14.setGeometry(QRect(20, 800, 101, 30))
        icon6 = QIcon()
        icon6.addFile(u"../../Downloads/sign out white.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon6.addFile(u"../../Downloads/sign-out.png", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        self.pushButton_14.setIcon(icon6)
        self.pushButton_14.setIconSize(QSize(25, 25))
        self.pushButton_14.setCheckable(True)
        self.pushButton_14.setAutoExclusive(True)
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(320, 0, 1121, 871))
        self.stackedWidget.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.dashboard = QWidget()
        self.dashboard.setObjectName(u"dashboard")
        self.frame = QFrame(self.dashboard)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(30, 150, 291, 231))
        self.frame.setStyleSheet(u"QWidget{\n"
"	background-color: rgb(173, 207, 239);\n"
"}")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.pending_title_label = QLabel(self.frame)
        self.pending_title_label.setObjectName(u"pending_title_label")
        self.pending_title_label.setGeometry(QRect(60, 10, 171, 41))
        self.pending_title_label.setFont(font)
        self.pending_title_label.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pending_count_label = QLabel(self.frame)
        self.pending_count_label.setObjectName(u"pending_count_label")
        self.pending_count_label.setGeometry(QRect(120, 90, 41, 41))
        self.pending_count_label.setFont(font)
        self.pending_count_label.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.frame_2 = QFrame(self.dashboard)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(370, 150, 291, 231))
        self.frame_2.setStyleSheet(u"QWidget{\n"
"	background-color: rgb(173, 207, 239);\n"
"}")
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.allocated_title_label = QLabel(self.frame_2)
        self.allocated_title_label.setObjectName(u"allocated_title_label")
        self.allocated_title_label.setGeometry(QRect(60, 10, 171, 41))
        self.allocated_title_label.setFont(font)
        self.allocated_title_label.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.allocated_count_label = QLabel(self.frame_2)
        self.allocated_count_label.setObjectName(u"allocated_count_label")
        self.allocated_count_label.setGeometry(QRect(120, 90, 41, 41))
        self.allocated_count_label.setFont(font)
        self.allocated_count_label.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.frame_3 = QFrame(self.dashboard)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(700, 150, 291, 231))
        self.frame_3.setStyleSheet(u"QWidget{\n"
"	background-color: rgb(173, 207, 239);\n"
"}")
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.exited_title_label = QLabel(self.frame_3)
        self.exited_title_label.setObjectName(u"exited_title_label")
        self.exited_title_label.setGeometry(QRect(110, 10, 61, 41))
        self.exited_title_label.setFont(font)
        self.exited_title_label.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pending_count_label_3 = QLabel(self.frame_3)
        self.pending_count_label_3.setObjectName(u"pending_count_label_3")
        self.pending_count_label_3.setGeometry(QRect(120, 90, 41, 41))
        self.pending_count_label_3.setFont(font)
        self.pending_count_label_3.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.exited_count_label = QLabel(self.frame_3)
        self.exited_count_label.setObjectName(u"exited_count_label")
        self.exited_count_label.setGeometry(QRect(120, 100, 41, 41))
        self.exited_count_label.setFont(font)
        self.exited_count_label.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.menu_button_1 = QPushButton(self.dashboard)
        self.menu_button_1.setObjectName(u"menu_button_1")
        self.menu_button_1.setGeometry(QRect(30, 80, 71, 51))
        self.menu_button_1.setStyleSheet(u"QWidget{\n"
"	background-color: rgb(173, 207, 239);\n"
"}")
        icon7 = QIcon()
        icon7.addFile(u":/sidebar_images/navbar_icon_white-removebg-preview.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.menu_button_1.setIcon(icon7)
        self.menu_button_1.setIconSize(QSize(90, 90))
        self.menu_button_1.setCheckable(True)
        self.listView = QListView(self.dashboard)
        self.listView.setObjectName(u"listView")
        self.listView.setGeometry(QRect(30, 400, 1071, 441))
        self.listView.setStyleSheet(u"QWidget{\n"
"	background-color: rgb(173, 207, 239);\n"
"}")
        self.pending_title_label_2 = QLabel(self.dashboard)
        self.pending_title_label_2.setObjectName(u"pending_title_label_2")
        self.pending_title_label_2.setGeometry(QRect(50, 410, 231, 41))
        self.pending_title_label_2.setFont(font)
        self.pending_title_label_2.setStyleSheet(u"background-color: rgb(173, 207, 239);\n"
"color: rgb(255, 255, 255);")
        self.dashboard_label = QLabel(self.dashboard)
        self.dashboard_label.setObjectName(u"dashboard_label")
        self.dashboard_label.setGeometry(QRect(30, 20, 221, 41))
        font1 = QFont()
        font1.setPointSize(30)
        self.dashboard_label.setFont(font1)
        self.stackedWidget.addWidget(self.dashboard)
        self.licensemanagement_2 = QWidget()
        self.licensemanagement_2.setObjectName(u"licensemanagement_2")
        self.header_widget_2 = QWidget(self.licensemanagement_2)
        self.header_widget_2.setObjectName(u"header_widget_2")
        self.header_widget_2.setGeometry(QRect(10, 70, 1091, 94))
        self.pushButton_8 = QPushButton(self.header_widget_2)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(680, 10, 111, 51))
        self.pushButton_8.setStyleSheet(u"QWidget{\n"
"	background-color: rgb(173, 207, 239);\n"
"	height: 30px;\n"
"}\n"
"")
        icon8 = QIcon()
        icon8.addFile(u":/sidebar_images/Blue search icon.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_8.setIcon(icon8)
        self.pushButton_8.setIconSize(QSize(25, 25))
        self.lineEdit_2 = QLineEdit(self.header_widget_2)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(130, 20, 531, 31))
        self.menu_button_2 = QPushButton(self.header_widget_2)
        self.menu_button_2.setObjectName(u"menu_button_2")
        self.menu_button_2.setGeometry(QRect(20, 10, 71, 51))
        self.menu_button_2.setStyleSheet(u"QWidget{\n"
"	background-color: rgb(173, 207, 239);\n"
"}")
        self.menu_button_2.setIcon(icon7)
        self.menu_button_2.setIconSize(QSize(90, 90))
        self.menu_button_2.setCheckable(True)
        self.frame_5 = QFrame(self.licensemanagement_2)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setGeometry(QRect(40, 150, 321, 671))
        self.frame_5.setStyleSheet(u"QFrame{\n"
"	background-color: rgb(173, 207, 239);\n"
"}")
        self.frame_5.setFrameShape(QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QFrame.Raised)
        self.pending_label = QLabel(self.frame_5)
        self.pending_label.setObjectName(u"pending_label")
        self.pending_label.setGeometry(QRect(120, 20, 91, 51))
        font2 = QFont()
        font2.setPointSize(25)
        self.pending_label.setFont(font2)
        self.pending_label.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pending_count2_label = QLabel(self.frame_5)
        self.pending_count2_label.setObjectName(u"pending_count2_label")
        self.pending_count2_label.setGeometry(QRect(120, 70, 91, 51))
        self.pending_count2_label.setFont(font2)
        self.pending_count2_label.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.line = QFrame(self.frame_5)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(0, 140, 321, 31))
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.listWidget = QListWidget(self.frame_5)
        self.listWidget.setObjectName(u"listWidget")
        self.listWidget.setGeometry(QRect(30, 220, 256, 411))
        self.listWidget.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.verticalScrollBar_2 = QScrollBar(self.frame_5)
        self.verticalScrollBar_2.setObjectName(u"verticalScrollBar_2")
        self.verticalScrollBar_2.setGeometry(QRect(270, 220, 21, 401))
        self.verticalScrollBar_2.setStyleSheet(u"background-color: rgb(157, 157, 157);")
        self.verticalScrollBar_2.setOrientation(Qt.Vertical)
        self.widget_3 = QWidget(self.frame_5)
        self.widget_3.setObjectName(u"widget_3")
        self.widget_3.setGeometry(QRect(70, 240, 171, 71))
        self.label_9 = QLabel(self.widget_3)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 40, 61, 16))
        font3 = QFont()
        font3.setKerning(True)
        self.label_9.setFont(font3)
        self.label_9.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_10 = QLabel(self.widget_3)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 20, 21, 16))
        self.label_10.setFont(font3)
        self.label_10.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_11 = QLabel(self.widget_3)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 0, 41, 16))
        self.label_11.setFont(font3)
        self.label_11.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.pending_name_label_2 = QLabel(self.widget_3)
        self.pending_name_label_2.setObjectName(u"pending_name_label_2")
        self.pending_name_label_2.setGeometry(QRect(60, 0, 111, 16))
        self.pending_name_label_2.setFont(font3)
        self.pending_name_label_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.id_name_label_2 = QLabel(self.widget_3)
        self.id_name_label_2.setObjectName(u"id_name_label_2")
        self.id_name_label_2.setGeometry(QRect(40, 20, 161, 16))
        self.id_name_label_2.setFont(font3)
        self.id_name_label_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.release_name_label_2 = QLabel(self.widget_3)
        self.release_name_label_2.setObjectName(u"release_name_label_2")
        self.release_name_label_2.setGeometry(QRect(70, 40, 121, 16))
        self.release_name_label_2.setFont(font3)
        self.release_name_label_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.add_pending_button = QPushButton(self.frame_5)
        self.add_pending_button.setObjectName(u"add_pending_button")
        self.add_pending_button.setGeometry(QRect(190, 170, 41, 41))
        self.add_pending_button.setStyleSheet(u"QWidget{\n"
"	background-color: rgb(173, 207, 239);\n"
"	height: 30px;\n"
"}\n"
"")
        icon9 = QIcon()
        icon9.addFile(u"../../Downloads/add-on-white.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon9.addFile(u"../../Downloads/add-button.png", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        self.add_pending_button.setIcon(icon9)
        self.add_pending_button.setIconSize(QSize(25, 25))
        self.label_2 = QLabel(self.frame_5)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(80, 180, 91, 16))
        font4 = QFont()
        font4.setPointSize(15)
        self.label_2.setFont(font4)
        self.frame_6 = QFrame(self.licensemanagement_2)
        self.frame_6.setObjectName(u"frame_6")
        self.frame_6.setGeometry(QRect(380, 150, 321, 671))
        self.frame_6.setStyleSheet(u"QFrame{\n"
"	background-color: rgb(173, 207, 239);\n"
"}")
        self.frame_6.setFrameShape(QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QFrame.Raised)
        self.allocated_label = QLabel(self.frame_6)
        self.allocated_label.setObjectName(u"allocated_label")
        self.allocated_label.setGeometry(QRect(100, 20, 111, 51))
        self.allocated_label.setFont(font2)
        self.allocated_label.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.allocated_count2_label = QLabel(self.frame_6)
        self.allocated_count2_label.setObjectName(u"allocated_count2_label")
        self.allocated_count2_label.setGeometry(QRect(100, 70, 91, 51))
        self.allocated_count2_label.setFont(font2)
        self.allocated_count2_label.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.line_2 = QFrame(self.frame_6)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(0, 140, 321, 31))
        self.line_2.setFrameShape(QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QFrame.Shadow.Sunken)
        self.listWidget_4 = QListWidget(self.frame_6)
        self.listWidget_4.setObjectName(u"listWidget_4")
        self.listWidget_4.setGeometry(QRect(30, 220, 256, 411))
        self.listWidget_4.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.verticalScrollBar_3 = QScrollBar(self.frame_6)
        self.verticalScrollBar_3.setObjectName(u"verticalScrollBar_3")
        self.verticalScrollBar_3.setGeometry(QRect(270, 220, 21, 401))
        self.verticalScrollBar_3.setStyleSheet(u"background-color: rgb(157, 157, 157);")
        self.verticalScrollBar_3.setOrientation(Qt.Vertical)
        self.allocated_widget = QWidget(self.frame_6)
        self.allocated_widget.setObjectName(u"allocated_widget")
        self.allocated_widget.setGeometry(QRect(70, 230, 171, 71))
        self.label_15 = QLabel(self.allocated_widget)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(10, 40, 61, 16))
        self.label_15.setFont(font3)
        self.label_15.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_16 = QLabel(self.allocated_widget)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(10, 20, 21, 16))
        self.label_16.setFont(font3)
        self.label_16.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.allocated_name_label = QLabel(self.allocated_widget)
        self.allocated_name_label.setObjectName(u"allocated_name_label")
        self.allocated_name_label.setGeometry(QRect(10, 0, 41, 16))
        self.allocated_name_label.setFont(font3)
        self.allocated_name_label.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.allocated_name_label_2 = QLabel(self.allocated_widget)
        self.allocated_name_label_2.setObjectName(u"allocated_name_label_2")
        self.allocated_name_label_2.setGeometry(QRect(60, 0, 111, 16))
        self.allocated_name_label_2.setFont(font3)
        self.allocated_name_label_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.allocated_id_label = QLabel(self.allocated_widget)
        self.allocated_id_label.setObjectName(u"allocated_id_label")
        self.allocated_id_label.setGeometry(QRect(40, 20, 161, 16))
        self.allocated_id_label.setFont(font3)
        self.allocated_id_label.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.release_name_label_4 = QLabel(self.allocated_widget)
        self.release_name_label_4.setObjectName(u"release_name_label_4")
        self.release_name_label_4.setGeometry(QRect(70, 40, 121, 16))
        self.release_name_label_4.setFont(font3)
        self.release_name_label_4.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.allocated_widget_2 = QWidget(self.allocated_widget)
        self.allocated_widget_2.setObjectName(u"allocated_widget_2")
        self.allocated_widget_2.setGeometry(QRect(150, 70, 171, 71))
        self.label_17 = QLabel(self.allocated_widget_2)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(10, 40, 61, 16))
        self.label_17.setFont(font3)
        self.label_17.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_18 = QLabel(self.allocated_widget_2)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(10, 20, 21, 16))
        self.label_18.setFont(font3)
        self.label_18.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.allocated_name_label_3 = QLabel(self.allocated_widget_2)
        self.allocated_name_label_3.setObjectName(u"allocated_name_label_3")
        self.allocated_name_label_3.setGeometry(QRect(10, 0, 41, 16))
        self.allocated_name_label_3.setFont(font3)
        self.allocated_name_label_3.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.allocated_name_label_4 = QLabel(self.allocated_widget_2)
        self.allocated_name_label_4.setObjectName(u"allocated_name_label_4")
        self.allocated_name_label_4.setGeometry(QRect(60, 0, 111, 16))
        self.allocated_name_label_4.setFont(font3)
        self.allocated_name_label_4.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.allocated_id_label_2 = QLabel(self.allocated_widget_2)
        self.allocated_id_label_2.setObjectName(u"allocated_id_label_2")
        self.allocated_id_label_2.setGeometry(QRect(40, 20, 161, 16))
        self.allocated_id_label_2.setFont(font3)
        self.allocated_id_label_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.release_name_label_5 = QLabel(self.allocated_widget_2)
        self.release_name_label_5.setObjectName(u"release_name_label_5")
        self.release_name_label_5.setGeometry(QRect(70, 40, 121, 16))
        self.release_name_label_5.setFont(font3)
        self.release_name_label_5.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_3 = QLabel(self.frame_6)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(80, 180, 91, 16))
        self.label_3.setFont(font4)
        self.add_allocated_button = QPushButton(self.frame_6)
        self.add_allocated_button.setObjectName(u"add_allocated_button")
        self.add_allocated_button.setGeometry(QRect(190, 170, 41, 41))
        self.add_allocated_button.setStyleSheet(u"QWidget{\n"
"	background-color: rgb(173, 207, 239);\n"
"	height: 30px;\n"
"}\n"
"")
        self.add_allocated_button.setIcon(icon9)
        self.add_allocated_button.setIconSize(QSize(25, 25))
        self.frame_7 = QFrame(self.licensemanagement_2)
        self.frame_7.setObjectName(u"frame_7")
        self.frame_7.setGeometry(QRect(730, 150, 321, 671))
        self.frame_7.setStyleSheet(u"QFrame{\n"
"	background-color: rgb(173, 207, 239);\n"
"}")
        self.frame_7.setFrameShape(QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QFrame.Raised)
        self.exited_label = QLabel(self.frame_7)
        self.exited_label.setObjectName(u"exited_label")
        self.exited_label.setGeometry(QRect(130, 30, 91, 51))
        self.exited_label.setFont(font2)
        self.exited_label.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.exited_count2_label = QLabel(self.frame_7)
        self.exited_count2_label.setObjectName(u"exited_count2_label")
        self.exited_count2_label.setGeometry(QRect(130, 80, 91, 51))
        self.exited_count2_label.setFont(font2)
        self.exited_count2_label.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.line_3 = QFrame(self.frame_7)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(0, 140, 321, 31))
        self.line_3.setFrameShape(QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QFrame.Shadow.Sunken)
        self.listWidget_3 = QListWidget(self.frame_7)
        self.listWidget_3.setObjectName(u"listWidget_3")
        self.listWidget_3.setGeometry(QRect(30, 220, 256, 411))
        self.listWidget_3.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.verticalScrollBar_4 = QScrollBar(self.frame_7)
        self.verticalScrollBar_4.setObjectName(u"verticalScrollBar_4")
        self.verticalScrollBar_4.setGeometry(QRect(265, 220, 21, 401))
        self.verticalScrollBar_4.setStyleSheet(u"background-color: rgb(157, 157, 157);")
        self.verticalScrollBar_4.setOrientation(Qt.Vertical)
        self.allocated_widget_3 = QWidget(self.frame_7)
        self.allocated_widget_3.setObjectName(u"allocated_widget_3")
        self.allocated_widget_3.setGeometry(QRect(70, 230, 171, 71))
        self.label_19 = QLabel(self.allocated_widget_3)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(10, 40, 61, 16))
        self.label_19.setFont(font3)
        self.label_19.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_20 = QLabel(self.allocated_widget_3)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(10, 20, 21, 16))
        self.label_20.setFont(font3)
        self.label_20.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.allocated_name_label_5 = QLabel(self.allocated_widget_3)
        self.allocated_name_label_5.setObjectName(u"allocated_name_label_5")
        self.allocated_name_label_5.setGeometry(QRect(10, 0, 41, 16))
        self.allocated_name_label_5.setFont(font3)
        self.allocated_name_label_5.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.allocated_name_label_6 = QLabel(self.allocated_widget_3)
        self.allocated_name_label_6.setObjectName(u"allocated_name_label_6")
        self.allocated_name_label_6.setGeometry(QRect(60, 0, 111, 16))
        self.allocated_name_label_6.setFont(font3)
        self.allocated_name_label_6.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.exited_id_label = QLabel(self.allocated_widget_3)
        self.exited_id_label.setObjectName(u"exited_id_label")
        self.exited_id_label.setGeometry(QRect(40, 20, 161, 16))
        self.exited_id_label.setFont(font3)
        self.exited_id_label.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.release_name_label_6 = QLabel(self.allocated_widget_3)
        self.release_name_label_6.setObjectName(u"release_name_label_6")
        self.release_name_label_6.setGeometry(QRect(70, 40, 121, 16))
        self.release_name_label_6.setFont(font3)
        self.release_name_label_6.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.allocated_widget_4 = QWidget(self.allocated_widget_3)
        self.allocated_widget_4.setObjectName(u"allocated_widget_4")
        self.allocated_widget_4.setGeometry(QRect(150, 70, 171, 71))
        self.label_21 = QLabel(self.allocated_widget_4)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(10, 40, 61, 16))
        self.label_21.setFont(font3)
        self.label_21.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_22 = QLabel(self.allocated_widget_4)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(10, 20, 21, 16))
        self.label_22.setFont(font3)
        self.label_22.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.allocated_name_label_7 = QLabel(self.allocated_widget_4)
        self.allocated_name_label_7.setObjectName(u"allocated_name_label_7")
        self.allocated_name_label_7.setGeometry(QRect(10, 0, 41, 16))
        self.allocated_name_label_7.setFont(font3)
        self.allocated_name_label_7.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.allocated_name_label_8 = QLabel(self.allocated_widget_4)
        self.allocated_name_label_8.setObjectName(u"allocated_name_label_8")
        self.allocated_name_label_8.setGeometry(QRect(60, 0, 111, 16))
        self.allocated_name_label_8.setFont(font3)
        self.allocated_name_label_8.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.allocated_id_label_4 = QLabel(self.allocated_widget_4)
        self.allocated_id_label_4.setObjectName(u"allocated_id_label_4")
        self.allocated_id_label_4.setGeometry(QRect(40, 20, 161, 16))
        self.allocated_id_label_4.setFont(font3)
        self.allocated_id_label_4.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.release_name_label_7 = QLabel(self.allocated_widget_4)
        self.release_name_label_7.setObjectName(u"release_name_label_7")
        self.release_name_label_7.setGeometry(QRect(70, 40, 121, 16))
        self.release_name_label_7.setFont(font3)
        self.release_name_label_7.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_5 = QLabel(self.frame_7)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(70, 180, 91, 16))
        self.label_5.setFont(font4)
        self.add_exited_button = QPushButton(self.frame_7)
        self.add_exited_button.setObjectName(u"add_exited_button")
        self.add_exited_button.setGeometry(QRect(180, 170, 41, 41))
        self.add_exited_button.setStyleSheet(u"QWidget{\n"
"	background-color: rgb(173, 207, 239);\n"
"	height: 30px;\n"
"}\n"
"")
        self.add_exited_button.setIcon(icon9)
        self.add_exited_button.setIconSize(QSize(25, 25))
        self.license_management_label = QLabel(self.licensemanagement_2)
        self.license_management_label.setObjectName(u"license_management_label")
        self.license_management_label.setGeometry(QRect(40, 20, 381, 41))
        self.license_management_label.setFont(font1)
        self.stackedWidget.addWidget(self.licensemanagement_2)
        self.RHU_management = QWidget()
        self.RHU_management.setObjectName(u"RHU_management")
        self.header_widget_4 = QWidget(self.RHU_management)
        self.header_widget_4.setObjectName(u"header_widget_4")
        self.header_widget_4.setGeometry(QRect(20, 60, 1141, 94))
        self.menu_button_3 = QPushButton(self.header_widget_4)
        self.menu_button_3.setObjectName(u"menu_button_3")
        self.menu_button_3.setGeometry(QRect(30, 10, 71, 51))
        self.menu_button_3.setStyleSheet(u"QWidget{\n"
"	background-color: rgb(173, 207, 239);\n"
"}")
        self.menu_button_3.setIcon(icon7)
        self.menu_button_3.setIconSize(QSize(90, 90))
        self.menu_button_3.setCheckable(True)
        self.pushButton_22 = QPushButton(self.header_widget_4)
        self.pushButton_22.setObjectName(u"pushButton_22")
        self.pushButton_22.setGeometry(QRect(1010, 10, 61, 51))
        self.pushButton_22.setStyleSheet(u"QWidget{\n"
"	background-color: rgb(173, 207, 239);\n"
"	height: 30px;\n"
"}\n"
"")
        self.pushButton_22.setIcon(icon9)
        self.pushButton_22.setIconSize(QSize(25, 25))
        self.lineEdit_4 = QLineEdit(self.header_widget_4)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setGeometry(QRect(270, 20, 721, 31))
        self.frame_8 = QFrame(self.RHU_management)
        self.frame_8.setObjectName(u"frame_8")
        self.frame_8.setGeometry(QRect(20, 170, 531, 681))
        self.frame_8.setStyleSheet(u"QFrame{\n"
"	background-color: rgb(173, 207, 239);\n"
"}")
        self.frame_8.setFrameShape(QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QFrame.Raised)
        self.label_6 = QLabel(self.frame_8)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(30, 20, 111, 21))
        font5 = QFont()
        font5.setPointSize(20)
        font5.setBold(False)
        font5.setUnderline(False)
        self.label_6.setFont(font5)
        self.verticalScrollBar_5 = QScrollBar(self.frame_8)
        self.verticalScrollBar_5.setObjectName(u"verticalScrollBar_5")
        self.verticalScrollBar_5.setGeometry(QRect(510, 10, 16, 661))
        self.verticalScrollBar_5.setOrientation(Qt.Vertical)
        self.widget_2 = QWidget(self.frame_8)
        self.widget_2.setObjectName(u"widget_2")
        self.widget_2.setGeometry(QRect(30, 60, 461, 101))
        self.label_27 = QLabel(self.widget_2)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(10, 10, 51, 21))
        self.label_27.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_28 = QLabel(self.widget_2)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(10, 30, 61, 21))
        self.label_28.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_29 = QLabel(self.widget_2)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(120, 30, 61, 21))
        self.label_29.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_30 = QLabel(self.widget_2)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(10, 50, 101, 21))
        self.label_30.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_31 = QLabel(self.widget_2)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(10, 70, 51, 21))
        self.label_31.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.rhu_list_name_label_2 = QLabel(self.widget_2)
        self.rhu_list_name_label_2.setObjectName(u"rhu_list_name_label_2")
        self.rhu_list_name_label_2.setGeometry(QRect(60, 10, 51, 21))
        self.rhu_list_name_label_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.rhu_list_capacity_label_2 = QLabel(self.widget_2)
        self.rhu_list_capacity_label_2.setObjectName(u"rhu_list_capacity_label_2")
        self.rhu_list_capacity_label_2.setGeometry(QRect(70, 30, 31, 21))
        self.rhu_list_capacity_label_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.rhu_list_current_label_2 = QLabel(self.widget_2)
        self.rhu_list_current_label_2.setObjectName(u"rhu_list_current_label_2")
        self.rhu_list_current_label_2.setGeometry(QRect(170, 30, 31, 21))
        self.rhu_list_current_label_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.frame_9 = QFrame(self.RHU_management)
        self.frame_9.setObjectName(u"frame_9")
        self.frame_9.setGeometry(QRect(570, 170, 531, 681))
        self.frame_9.setStyleSheet(u"QFrame{\n"
"	background-color: rgb(173, 207, 239);\n"
"}")
        self.frame_9.setFrameShape(QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QFrame.Raised)
        self.label_7 = QLabel(self.frame_9)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(20, 20, 111, 21))
        self.label_7.setFont(font5)
        self.widget = QWidget(self.frame_9)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(20, 70, 471, 231))
        self.label_32 = QLabel(self.widget)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(10, 30, 61, 21))
        self.label_32.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_33 = QLabel(self.widget)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(10, 0, 181, 21))
        self.label_33.setFont(font)
        self.label_33.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_34 = QLabel(self.widget)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(10, 60, 61, 21))
        self.label_34.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_35 = QLabel(self.widget)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(10, 90, 61, 21))
        self.label_35.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_36 = QLabel(self.widget)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(10, 120, 61, 21))
        self.label_36.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_8 = QLabel(self.widget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(80, 30, 60, 16))
        self.label_8.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_23 = QLabel(self.widget)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(60, 60, 60, 16))
        self.label_23.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.email_label = QLabel(self.widget)
        self.email_label.setObjectName(u"email_label")
        self.email_label.setGeometry(QRect(70, 90, 60, 16))
        self.email_label.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.RHU_management_label = QLabel(self.widget)
        self.RHU_management_label.setObjectName(u"RHU_management_label")
        self.RHU_management_label.setGeometry(QRect(80, 120, 60, 16))
        self.RHU_management_label.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label = QLabel(self.RHU_management)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(40, 20, 341, 31))
        self.label.setFont(font1)
        self.stackedWidget.addWidget(self.RHU_management)
        self.Allocation_matching = QWidget()
        self.Allocation_matching.setObjectName(u"Allocation_matching")
        self.menu_button_4 = QPushButton(self.Allocation_matching)
        self.menu_button_4.setObjectName(u"menu_button_4")
        self.menu_button_4.setGeometry(QRect(30, 70, 71, 51))
        self.menu_button_4.setStyleSheet(u"QWidget{\n"
"	background-color: rgb(173, 207, 239);\n"
"}")
        self.menu_button_4.setIcon(icon7)
        self.menu_button_4.setIconSize(QSize(90, 90))
        self.menu_button_4.setCheckable(True)
        self.verticalScrollBar_7 = QScrollBar(self.Allocation_matching)
        self.verticalScrollBar_7.setObjectName(u"verticalScrollBar_7")
        self.verticalScrollBar_7.setGeometry(QRect(1060, 440, 16, 341))
        self.verticalScrollBar_7.setOrientation(Qt.Vertical)
        self.allocation_container = QFrame(self.Allocation_matching)
        self.allocation_container.setObjectName(u"allocation_container")
        self.allocation_container.setGeometry(QRect(30, 140, 1061, 691))
        self.allocation_container.setFrameShape(QFrame.StyledPanel)
        self.allocation_container.setFrameShadow(QFrame.Raised)
        self.split_area = QWidget(self.allocation_container)
        self.split_area.setObjectName(u"split_area")
        self.split_area.setGeometry(QRect(10, 10, 1021, 651))
        self.left_panel = QWidget(self.split_area)
        self.left_panel.setObjectName(u"left_panel")
        self.left_panel.setGeometry(QRect(10, 10, 361, 631))
        self.left_panel.setStyleSheet(u"QWidget{\n"
"	background-color: rgb(173, 207, 239);\n"
"}")
        self.select_license_label = QLabel(self.left_panel)
        self.select_license_label.setObjectName(u"select_license_label")
        self.select_license_label.setGeometry(QRect(10, 10, 181, 16))
        self.select_license_label.setFont(font)
        self.select_license_label.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.search_box = QLineEdit(self.left_panel)
        self.search_box.setObjectName(u"search_box")
        self.search_box.setGeometry(QRect(20, 40, 321, 21))
        self.search_box.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.prisoner_list_widget = QListWidget(self.left_panel)
        self.prisoner_list_widget.setObjectName(u"prisoner_list_widget")
        self.prisoner_list_widget.setGeometry(QRect(20, 70, 321, 551))
        self.right_name = QWidget(self.split_area)
        self.right_name.setObjectName(u"right_name")
        self.right_name.setGeometry(QRect(390, 10, 611, 591))
        self.right_name.setStyleSheet(u"QWidget{\n"
"	background-color: rgb(173, 207, 239);\n"
"}")
        self.prisoner_info_label = QLabel(self.right_name)
        self.prisoner_info_label.setObjectName(u"prisoner_info_label")
        self.prisoner_info_label.setGeometry(QRect(10, 10, 411, 31))
        self.prisoner_info_label.setFont(font)
        self.prisoner_info_label.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.rhu_container = QScrollArea(self.right_name)
        self.rhu_container.setObjectName(u"rhu_container")
        self.rhu_container.setGeometry(QRect(30, 60, 571, 511))
        self.rhu_container.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 569, 509))
        self.verticalLayoutWidget = QWidget(self.scrollAreaWidgetContents)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(-10, 0, 581, 511))
        self.rhu_container_layout = QVBoxLayout(self.verticalLayoutWidget)
        self.rhu_container_layout.setObjectName(u"rhu_container_layout")
        self.rhu_container_layout.setContentsMargins(0, 0, 0, 0)
        self.rhu_container.setWidget(self.scrollAreaWidgetContents)
        self.button_area = QWidget(self.split_area)
        self.button_area.setObjectName(u"button_area")
        self.button_area.setGeometry(QRect(390, 610, 611, 51))
        self.button_area.setStyleSheet(u"QWidget{\n"
"	background-color: rgb(173, 207, 239);\n"
"}")
        self.allocate_button = QPushButton(self.button_area)
        self.allocate_button.setObjectName(u"allocate_button")
        self.allocate_button.setGeometry(QRect(10, 0, 191, 32))
        self.cancel_button = QPushButton(self.button_area)
        self.cancel_button.setObjectName(u"cancel_button")
        self.cancel_button.setGeometry(QRect(260, 0, 131, 32))
        self.label_12 = QLabel(self.Allocation_matching)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(30, 20, 331, 41))
        self.label_12.setFont(font1)
        self.stackedWidget.addWidget(self.Allocation_matching)
        self.Release_management = QWidget()
        self.Release_management.setObjectName(u"Release_management")
        self.header_widget_7 = QWidget(self.Release_management)
        self.header_widget_7.setObjectName(u"header_widget_7")
        self.header_widget_7.setGeometry(QRect(20, 60, 1141, 61))
        self.menu_button_5 = QPushButton(self.header_widget_7)
        self.menu_button_5.setObjectName(u"menu_button_5")
        self.menu_button_5.setGeometry(QRect(30, 10, 71, 51))
        self.menu_button_5.setStyleSheet(u"QWidget{\n"
"	background-color: rgb(173, 207, 239);\n"
"}")
        self.menu_button_5.setIcon(icon7)
        self.menu_button_5.setIconSize(QSize(90, 90))
        self.menu_button_5.setCheckable(True)
        self.widget_6 = QWidget(self.Release_management)
        self.widget_6.setObjectName(u"widget_6")
        self.widget_6.setGeometry(QRect(30, 170, 1051, 451))
        self.widget_6.setStyleSheet(u"border-color: rgb(90, 90, 90);")
        self.frame_12 = QFrame(self.widget_6)
        self.frame_12.setObjectName(u"frame_12")
        self.frame_12.setGeometry(QRect(20, 10, 1011, 31))
        self.frame_12.setStyleSheet(u"border-color: rgb(47, 47, 47);")
        self.frame_12.setFrameShape(QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QFrame.Raised)
        self.release_accomodation_label = QLabel(self.frame_12)
        self.release_accomodation_label.setObjectName(u"release_accomodation_label")
        self.release_accomodation_label.setGeometry(QRect(10, 5, 251, 21))
        font6 = QFont()
        font6.setPointSize(20)
        font6.setBold(True)
        self.release_accomodation_label.setFont(font6)
        self.releaseTableView = QTableView(self.widget_6)
        self.releaseTableView.setObjectName(u"releaseTableView")
        self.releaseTableView.setGeometry(QRect(30, 70, 991, 371))
        self.release_management_label = QLabel(self.Release_management)
        self.release_management_label.setObjectName(u"release_management_label")
        self.release_management_label.setGeometry(QRect(50, 10, 331, 41))
        self.release_management_label.setFont(font1)
        self.stackedWidget.addWidget(self.Release_management)
        self.cost_tracking = QWidget()
        self.cost_tracking.setObjectName(u"cost_tracking")
        self.header_widget_8 = QWidget(self.cost_tracking)
        self.header_widget_8.setObjectName(u"header_widget_8")
        self.header_widget_8.setGeometry(QRect(20, 60, 1141, 61))
        self.menu_button_6 = QPushButton(self.header_widget_8)
        self.menu_button_6.setObjectName(u"menu_button_6")
        self.menu_button_6.setGeometry(QRect(10, 10, 71, 51))
        self.menu_button_6.setStyleSheet(u"QWidget{\n"
"	background-color: rgb(173, 207, 239);\n"
"}")
        self.menu_button_6.setIcon(icon7)
        self.menu_button_6.setIconSize(QSize(90, 90))
        self.menu_button_6.setCheckable(True)
        self.frame_13 = QFrame(self.cost_tracking)
        self.frame_13.setObjectName(u"frame_13")
        self.frame_13.setGeometry(QRect(50, 140, 331, 141))
        self.frame_13.setStyleSheet(u"QWidget{\n"
"	background-color: rgb(173, 207, 239);\n"
"}")
        self.frame_13.setFrameShape(QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QFrame.Raised)
        self.label_39 = QLabel(self.frame_13)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(10, 0, 161, 21))
        self.label_39.setFont(font)
        self.total_daily_cost = QLabel(self.frame_13)
        self.total_daily_cost.setObjectName(u"total_daily_cost")
        self.total_daily_cost.setGeometry(QRect(80, 60, 161, 21))
        self.total_daily_cost.setFont(font)
        self.frame_14 = QFrame(self.cost_tracking)
        self.frame_14.setObjectName(u"frame_14")
        self.frame_14.setGeometry(QRect(400, 140, 331, 141))
        self.frame_14.setStyleSheet(u"QWidget{\n"
"	background-color: rgb(173, 207, 239);\n"
"}")
        self.frame_14.setFrameShape(QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QFrame.Raised)
        self.label_42 = QLabel(self.frame_14)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(0, 0, 161, 21))
        self.label_42.setFont(font)
        self.monthly_budget_label = QLabel(self.frame_14)
        self.monthly_budget_label.setObjectName(u"monthly_budget_label")
        self.monthly_budget_label.setGeometry(QRect(90, 60, 161, 21))
        self.monthly_budget_label.setFont(font)
        self.frame_15 = QFrame(self.cost_tracking)
        self.frame_15.setObjectName(u"frame_15")
        self.frame_15.setGeometry(QRect(750, 140, 331, 141))
        self.frame_15.setStyleSheet(u"QWidget{\n"
"	background-color: rgb(173, 207, 239);\n"
"}")
        self.frame_15.setFrameShape(QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QFrame.Raised)
        self.label_43 = QLabel(self.frame_15)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(10, 0, 191, 21))
        self.label_43.setFont(font)
        self.days_to_budget_label = QLabel(self.frame_15)
        self.days_to_budget_label.setObjectName(u"days_to_budget_label")
        self.days_to_budget_label.setGeometry(QRect(70, 70, 161, 21))
        self.days_to_budget_label.setFont(font)
        self.cost_tracking_label = QLabel(self.cost_tracking)
        self.cost_tracking_label.setObjectName(u"cost_tracking_label")
        self.cost_tracking_label.setGeometry(QRect(40, 10, 231, 41))
        self.cost_tracking_label.setFont(font1)
        self.stackedWidget.addWidget(self.cost_tracking)
        self.icon_widget = QWidget(self.centralwidget)
        self.icon_widget.setObjectName(u"icon_widget")
        self.icon_widget.setGeometry(QRect(0, 0, 81, 871))
        self.icon_widget.setStyleSheet(u"QWidget{\n"
"	background-color: rgb(173, 207, 239);\n"
"	height: 30px;\n"
"	border:none;\n"
"}\n"
"\n"
"QPushButton {\n"
"	color:white;\n"
"	text-align: left;\n"
"	height: 30px;\n"
"	border:none;\n"
"	border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"	background-color:white;\n"
"	color: rgb(173, 207, 239);\n"
"	font-weight:bold;\n"
"}\n"
"")
        self.signout_1 = QPushButton(self.icon_widget)
        self.signout_1.setObjectName(u"signout_1")
        self.signout_1.setGeometry(QRect(20, 800, 29, 30))
        self.signout_1.setIcon(icon6)
        self.signout_1.setIconSize(QSize(25, 50))
        self.signout_1.setCheckable(True)
        self.signout_1.setAutoExclusive(True)
        self.layoutWidget1 = QWidget(self.icon_widget)
        self.layoutWidget1.setObjectName(u"layoutWidget1")
        self.layoutWidget1.setGeometry(QRect(0, 20, 106, 252))
        self.Sidebar1 = QVBoxLayout(self.layoutWidget1)
        self.Sidebar1.setObjectName(u"Sidebar1")
        self.Sidebar1.setContentsMargins(0, 0, 0, 0)
        self.dashboard_1 = QPushButton(self.layoutWidget1)
        self.dashboard_1.setObjectName(u"dashboard_1")
        self.dashboard_1.setIcon(icon)
        self.dashboard_1.setIconSize(QSize(100, 100))
        self.dashboard_1.setCheckable(True)
        self.dashboard_1.setAutoExclusive(True)

        self.Sidebar1.addWidget(self.dashboard_1)

        self.license_1 = QPushButton(self.layoutWidget1)
        self.license_1.setObjectName(u"license_1")
        self.license_1.setIcon(icon1)
        self.license_1.setIconSize(QSize(100, 100))
        self.license_1.setCheckable(True)
        self.license_1.setAutoExclusive(True)

        self.Sidebar1.addWidget(self.license_1)

        self.RHU_1 = QPushButton(self.layoutWidget1)
        self.RHU_1.setObjectName(u"RHU_1")
        self.RHU_1.setIcon(icon2)
        self.RHU_1.setIconSize(QSize(100, 100))
        self.RHU_1.setCheckable(True)
        self.RHU_1.setAutoExclusive(True)

        self.Sidebar1.addWidget(self.RHU_1)

        self.allocation_1 = QPushButton(self.layoutWidget1)
        self.allocation_1.setObjectName(u"allocation_1")
        self.allocation_1.setIcon(icon3)
        self.allocation_1.setIconSize(QSize(100, 100))
        self.allocation_1.setCheckable(True)
        self.allocation_1.setAutoExclusive(True)

        self.Sidebar1.addWidget(self.allocation_1)

        self.release_1 = QPushButton(self.layoutWidget1)
        self.release_1.setObjectName(u"release_1")
        self.release_1.setIcon(icon4)
        self.release_1.setIconSize(QSize(100, 100))
        self.release_1.setCheckable(True)
        self.release_1.setAutoExclusive(True)

        self.Sidebar1.addWidget(self.release_1)

        self.cost_1 = QPushButton(self.layoutWidget1)
        self.cost_1.setObjectName(u"cost_1")
        self.cost_1.setIcon(icon5)
        self.cost_1.setIconSize(QSize(100, 100))
        self.cost_1.setCheckable(True)
        self.cost_1.setAutoExclusive(True)

        self.Sidebar1.addWidget(self.cost_1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.cost_1.toggled.connect(self.cost_2.setChecked)
        self.release_1.toggled.connect(self.release_2.setChecked)
        self.allocation_1.toggled.connect(self.allocation_2.setChecked)
        self.RHU_1.toggled.connect(self.RHU_2.setChecked)
        self.license_1.toggled.connect(self.license_2.setChecked)
        self.dashboard_1.toggled.connect(self.dashboard_2.setChecked)
        self.dashboard_2.toggled.connect(self.dashboard_1.setChecked)
        self.license_2.toggled.connect(self.license_1.setChecked)
        self.RHU_2.toggled.connect(self.RHU_1.setChecked)
        self.allocation_2.toggled.connect(self.allocation_1.setChecked)
        self.release_2.toggled.connect(self.release_1.setChecked)
        self.cost_2.toggled.connect(self.cost_1.setChecked)
        self.signout_1.toggled.connect(MainWindow.close)
        self.pushButton_14.toggled.connect(MainWindow.close)

        self.stackedWidget.setCurrentIndex(5)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label_4.setText("")
        self.dashboard_2.setText(QCoreApplication.translate("MainWindow", u"Dashboard", None))
        self.license_2.setText(QCoreApplication.translate("MainWindow", u"License Management", None))
        self.RHU_2.setText(QCoreApplication.translate("MainWindow", u"RHU Management", None))
        self.allocation_2.setText(QCoreApplication.translate("MainWindow", u"Allocation Matching", None))
        self.release_2.setText(QCoreApplication.translate("MainWindow", u"Release Management", None))
        self.cost_2.setText(QCoreApplication.translate("MainWindow", u"Cost Tracking", None))
        self.pushButton_14.setText(QCoreApplication.translate("MainWindow", u"Sign Out", None))
        self.pending_title_label.setText(QCoreApplication.translate("MainWindow", u"Pending allocations", None))
        self.pending_count_label.setText("")
        self.allocated_title_label.setText(QCoreApplication.translate("MainWindow", u"Currently allocated", None))
        self.allocated_count_label.setText("")
        self.exited_title_label.setText(QCoreApplication.translate("MainWindow", u"Exited", None))
        self.pending_count_label_3.setText("")
        self.exited_count_label.setText("")
        self.menu_button_1.setText("")
        self.pending_title_label_2.setText(QCoreApplication.translate("MainWindow", u"Urgent actions required:", None))
        self.dashboard_label.setText(QCoreApplication.translate("MainWindow", u"Dashboard", None))
        self.pushButton_8.setText(QCoreApplication.translate("MainWindow", u"Search", None))
        self.lineEdit_2.setText("")
        self.menu_button_2.setText("")
        self.pending_label.setText(QCoreApplication.translate("MainWindow", u"Pending ", None))
        self.pending_count2_label.setText("")
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Release:", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"ID:", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Name:", None))
        self.pending_name_label_2.setText("")
        self.id_name_label_2.setText("")
        self.release_name_label_2.setText("")
        self.add_pending_button.setText("")
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Add licence", None))
        self.allocated_label.setText(QCoreApplication.translate("MainWindow", u"Allocated", None))
        self.allocated_count2_label.setText("")
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Release:", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"ID:", None))
        self.allocated_name_label.setText(QCoreApplication.translate("MainWindow", u"Name:", None))
        self.allocated_name_label_2.setText("")
        self.allocated_id_label.setText("")
        self.release_name_label_4.setText("")
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Release:", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"ID:", None))
        self.allocated_name_label_3.setText(QCoreApplication.translate("MainWindow", u"Name:", None))
        self.allocated_name_label_4.setText("")
        self.allocated_id_label_2.setText("")
        self.release_name_label_5.setText("")
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Add licence", None))
        self.add_allocated_button.setText("")
        self.exited_label.setText(QCoreApplication.translate("MainWindow", u"Exited", None))
        self.exited_count2_label.setText("")
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"Release:", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"ID:", None))
        self.allocated_name_label_5.setText(QCoreApplication.translate("MainWindow", u"Name:", None))
        self.allocated_name_label_6.setText("")
        self.exited_id_label.setText("")
        self.release_name_label_6.setText("")
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"Release:", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"ID:", None))
        self.allocated_name_label_7.setText(QCoreApplication.translate("MainWindow", u"Name:", None))
        self.allocated_name_label_8.setText("")
        self.allocated_id_label_4.setText("")
        self.release_name_label_7.setText("")
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Add licence", None))
        self.add_exited_button.setText("")
        self.license_management_label.setText(QCoreApplication.translate("MainWindow", u"License management", None))
        self.menu_button_3.setText("")
        self.pushButton_22.setText("")
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"RHU list", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"Name:", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"Capacity:", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"Current:", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"Price (per day):", None))
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"Gender:", None))
        self.rhu_list_name_label_2.setText("")
        self.rhu_list_capacity_label_2.setText("")
        self.rhu_list_current_label_2.setText("")
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"RHU details:", None))
        self.label_32.setText(QCoreApplication.translate("MainWindow", u"Manager:", None))
        self.label_33.setText(QCoreApplication.translate("MainWindow", u"Contact information", None))
        self.label_34.setText(QCoreApplication.translate("MainWindow", u"Phone:", None))
        self.label_35.setText(QCoreApplication.translate("MainWindow", u"Email:", None))
        self.label_36.setText(QCoreApplication.translate("MainWindow", u"Location:", None))
        self.label_8.setText("")
        self.label_23.setText("")
        self.email_label.setText("")
        self.RHU_management_label.setText("")
        self.label.setText(QCoreApplication.translate("MainWindow", u"RHU Management", None))
        self.menu_button_4.setText("")
        self.select_license_label.setText(QCoreApplication.translate("MainWindow", u"Select License", None))
        self.search_box.setText(QCoreApplication.translate("MainWindow", u"Search...", None))
        self.prisoner_info_label.setText(QCoreApplication.translate("MainWindow", u"Select a prisoner to see matching RHUs", None))
        self.allocate_button.setText(QCoreApplication.translate("MainWindow", u"Allocated to selected RHU", None))
        self.cancel_button.setText(QCoreApplication.translate("MainWindow", u"Cancel", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Allocation Matching", None))
        self.menu_button_5.setText("")
        self.release_accomodation_label.setText("")
        self.release_management_label.setText(QCoreApplication.translate("MainWindow", u"Release Management", None))
        self.menu_button_6.setText("")
        self.label_39.setText(QCoreApplication.translate("MainWindow", u"Total daily cost:", None))
        self.total_daily_cost.setText("")
        self.label_42.setText(QCoreApplication.translate("MainWindow", u"Monthly budget", None))
        self.monthly_budget_label.setText("")
        self.label_43.setText(QCoreApplication.translate("MainWindow", u"Days to budget limit", None))
        self.days_to_budget_label.setText("")
        self.cost_tracking_label.setText(QCoreApplication.translate("MainWindow", u"Cost Tracking", None))
        self.signout_1.setText("")
        self.dashboard_1.setText("")
        self.license_1.setText("")
        self.RHU_1.setText("")
        self.allocation_1.setText("")
        self.release_1.setText("")
        self.cost_1.setText("")
    # retranslateUi

